logging:
  level:
    org.apache.kafka.clients.consumer: trace

spring:
  application:
    name: KafkaPollTimeoutTest

  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
#      max-poll-records: 5
      fetch-max-wait: 10
#      properties:
#        max.poll.interval.ms: 10000
